// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxsF7PTYWmSfQd331ooV92-VQccSjdRM4',
    appId: '1:19206117906:web:2666cd3f48ebac9d81d6cb',
    messagingSenderId: '19206117906',
    projectId: 'faculty-66bd7',
    authDomain: 'faculty-66bd7.firebaseapp.com',
    databaseURL: 'https://faculty-66bd7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'faculty-66bd7.firebasestorage.app',
    measurementId: 'G-57VRMCE3FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCoogLgUhEQqxtNmFTIU_DVURQVmF9BD8',
    appId: '1:19206117906:android:53a8dbd5a63811cb81d6cb',
    messagingSenderId: '19206117906',
    projectId: 'faculty-66bd7',
    databaseURL: 'https://faculty-66bd7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'faculty-66bd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZiPsNieDDjAKqAq3lC47Rndn5k2Y9TnI',
    appId: '1:19206117906:ios:320e9ff1df315e2581d6cb',
    messagingSenderId: '19206117906',
    projectId: 'faculty-66bd7',
    databaseURL: 'https://faculty-66bd7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'faculty-66bd7.firebasestorage.app',
    iosBundleId: 'com.example.myApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZiPsNieDDjAKqAq3lC47Rndn5k2Y9TnI',
    appId: '1:19206117906:ios:320e9ff1df315e2581d6cb',
    messagingSenderId: '19206117906',
    projectId: 'faculty-66bd7',
    databaseURL: 'https://faculty-66bd7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'faculty-66bd7.firebasestorage.app',
    iosBundleId: 'com.example.myApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxsF7PTYWmSfQd331ooV92-VQccSjdRM4',
    appId: '1:19206117906:web:a5e0bd612890d50381d6cb',
    messagingSenderId: '19206117906',
    projectId: 'faculty-66bd7',
    authDomain: 'faculty-66bd7.firebaseapp.com',
    databaseURL: 'https://faculty-66bd7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'faculty-66bd7.firebasestorage.app',
    measurementId: 'G-WERG7082JZ',
  );

}